language:
- node_js
node_js:
- '0.10'
env:
# - NODE_ENV='test'
- NODE_ENV=$TRAVIS_BRANCH
branches:
  only:
    - staging
    - production
install:
  - npm install -g grunt-cli
  - npm install -g bower
  - gem install sass
  - npm install
  - bower install
script:
  - grunt build
  - npm test
before_deploy:
  - rm -R node_modules
  - rm -R fonts/vectors
  - rm -R bower_components
  - rm -R .sass-cache
  - rm -R javascripts
  # - rm -R specs
  - rm -R stylesheets
deploy:
  - provider: elasticbeanstalk
    access_key_id: AKIAJ7BART2KY7QI45GA
    secret_access_key:
      secure: GzVdPHy8dYXOnwA6zhVIru6Dd4qbz/JQfq6S1PYOk5TlEYxWo/IjoZe6CfOotl55KpwPCLXls7mkstB1lzDlsl0XAXUq0ow87U2k6W0eT12+Vuxsil5eMFBmJE64ohG5EBPtanEle29kIqVLHxkqP/ivqiB+xMGS0rQz/ScGaPM=
    app: api
    env: api-env
    bucket_name: elasticbeanstalk-us-west-2-931267450346
    skip_cleanup: true
    region: us-west-2
    on:
      repo: thecolumnsproject/api
      branch: production
  - provider: elasticbeanstalk
    access_key_id: AKIAJ7BART2KY7QI45GA
    secret_access_key:
      secure: GzVdPHy8dYXOnwA6zhVIru6Dd4qbz/JQfq6S1PYOk5TlEYxWo/IjoZe6CfOotl55KpwPCLXls7mkstB1lzDlsl0XAXUq0ow87U2k6W0eT12+Vuxsil5eMFBmJE64ohG5EBPtanEle29kIqVLHxkqP/ivqiB+xMGS0rQz/ScGaPM=
    app: api
    env: api-stg-env
    bucket_name: elasticbeanstalk-us-west-2-931267450346
    skip_cleanup: true
    region: us-west-2
    on:
      repo: thecolumnsproject/api
      branch: staging
