language:
  - node_js
node_js:
  - '0.10'
env:
  - NODE_ENV='production'
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJ7BART2KY7QI45GA
  secret_access_key:
    secure: AarATxkp5lXPeVtZTbsihCyxtWcbmGs4U5aMqKNZpq1nQCKrCj6bJm/iOe+2kzhrAcI0TdUqc58m1mv3+H/Mw2yVfXgmEF+dfZwvvCerDKIincq1QAb/rb7k36Y+OQVDYKz+oyW90PNoUQ+4X7OROLAlSC1IbDVzMmhmu2niIww=
  app: api
  env: api-env
  bucket: elasticbeanstalk-us-west-2-931267450346
  region: us-west-2
  on:
    repo: thecolumnsproject/api